requirejs.config({
	"baseURL":"js",
	"paths":{
		//libs
		"Class":"libs/class",
		"Jquery":"libs/jquery",
		//classes
		"Launcher":"app/classes/Launcher",
		"Display":"app/classes/display/Display",
		"Game":"app/classes/Game",
		"ImageLoader":"app/classes/graphics/ImageLoader",
		"State":"app/classes/states/State",
		"GameState":"app/classes/states/GameState",
		"Handler":"app/classes/Handler",
		"KeyHandler":"app/classes/input/KeyHandler",
		"Entity":"app/classes/entities/Entity"
	}
});

require(['app/main']);